
//TODO: remove unused strings

Lazarus.locale.strings = Lazarus.locale.strings || {};

Lazarus.locale.strings['en'] = {

  "app.version": "unknown",
  "app.build": "unknown",
  "app.platform": "unknown",
  "app.name": "Lazarus: Form Recovery",
  "app.email": "lazarus@interclue.com",
  
  "generic.cancel": "Cancel",
  "generic.close": "Close",
  "generic.minutes": "minutes",
  "generic.hours": "hours",
  "generic.days": "days",
  "generic.or": "or",
  "generic.error.msg": "Sorry, an error occured and Lazarus was unable to complete the action",
  
  "disable.domain": "Disable Lazarus on this site",
  "disable.domain.tooltip": "Disable Lazarus for all pages on '{domain}'.",
  "disable.domain.confirm": "Are you sure you want to disable Lazarus for all pages on '{domain}'? \nThis will also remove all forms saved from {domain}.",
  "disable.domain.success": "Lazarus has been disabled for all pages on '{domain}'. \nTo re-enable any site remove it from the disabled sites list in the Lazarus options.",

  "menu.loading.saved.forms": "Fetching saved forms...",
  "menu.loading.saved.text": "Fetching saved forms...",
  "menu.logout": "Logout",
  "menu.logout.tooltip": "Logout to require a password before being able to restore forms again",
  "menu.no.saved.forms": "No saved forms found",
  "menu.no.saved.text": "No saved text found",
  "menu.enter.password": "Enter password...",
  "menu.enter.password.tooltip": "You'll need to enter your Lazarus password before you can recover this form",
  "menu.options": "Lazarus Options...",
  
  //options dialog
  "options.title": '{app.name}: Options',
  "options.versionInfo": 'Version: {app.platform} {app.version} (revision {app.build})',
  "options.about": "About",
  "options.about.html": "<p>Lazarus 3 is a complete rewrite, where we hope to solve two major architectural problems that exist in Lazarus 2, and also make a cross-browser codebase.</p><p>It is very much a beta product at the moment. The feature set will grow closer to the 2.x version as the various browser APIs allow.</p>",
  "options.contact": "Contact Us",
  "options.contact.html": '<p>Send bugreports and feature requests to <a href="mailto:{app.email}?subject=Lazarus%203%20for%20{app.platform}">{app.email}</a></p>',
  "options.debug": 'Debugging',
  "options.debugMode": 'Log Level',
	"options.debugMode.1": "Suppress all messages",
	"options.debugMode.2": "Log errors",
	"options.debugMode.3": "Log errors and warnings",
	"options.debugMode.4": "Log errors, warnings and messages",
	"options.general": "General",
  "options.password": "Security",
  "options.password.title": "Encrypt forms and require a password to restore text",
  "options.password.change": "Change password",
  "options.password.remove": "Remove password",
  "options.password.reset": "Reset password",
  "options.password.current": "Current password",
  "options.password.new": "Enter new password",
  "options.password.confirm": "Re-enter new password",
  "options.password.save": "Save new password",
  "options.general.title": "General Options",
  "options.whatToSave": "What to save",
  "options.expireForms": "Keep saved forms for",
  "options.expireForms.intervalTooLarge": "Forms can only be kept for a maximum of {days} days",
  "options.disabledDomains": "Disabled Sites",
  "options.security": "Security",
  "options.security.title": "Password",
  "options.database": "Database",
  "options.database.title": "Database Options",
  "options.databaseRebuilt": "Database rebuilt!",
  "options.experimental": "Experimental",
  "options.tooltip": "Edit your Lazarus options",
	"options.rebuildDatabase": "Rebuild the Database",
	"options.rebuildingDatabase": "Rebuilding database...",
	"options.savePasswords": "Save passwords",
	"options.saved": "Options saved.",
	"options.updates": "Updates",
	"options.updates.checking": "Checking for updates...",
	"options.updates.ok": "Lazarus is up to date (version {app.version}).",
	"options.updates.newVersionAvailable": '<a href="{url}" title="Install it now">A new version of Lazarus ({version}) is available!</a>',
	"options.updates.error": "An error occured when checking for updates.",
	"options.reset": "Reset to defaults",
	"options.reset.confirm": "Are you sure you want to reset all of your settings to their default values and remove all saved forms from the database?",
	"options.preferencesReset": "Preferences reset",
	"options.resettingPrefs": "Resetting preferences...",
	"options.sync": "Sync",
	"options.sync.title": "Lazarus Sync",
  "options.sync.info": 'When Lazarus sync comes out of beta it will be a <strong>paid for service</strong>, it <strong><em>will not be free</em></strong>.<br />For the reasons why please <a href="javascript:alert(\'TODO: link to blog post\')">read the blog post</a>. For now however, feel free to give it a go and <a href="mailto:{app.email}?subject=Lazarus%203%20for%20{app.platform}">tell me what you think</a>',
	"options.sync.setupAccount": "Setup a New Account",
	"options.sync.email": "Email Address",
	"options.sync.password": "Interclue Password",
	"options.sync.resetPassword": "Forgotten your password?",
	"options.sync.enterPassword": "Enter Password",
	"options.sync.confirmPassword": "Confirm Password",
	"options.sync.login": "Login",
	"options.sync.loginToInterclue": "Login to Interclue",
	"options.sync.loggingIn": "logging in...",
	"options.sync.loggedIn": "logged in.",
	"options.sync.createAccount": "Create a New Interclue Account",
	"options.sync.creatingAccount": "Creating account...",
	"options.sync.createdAccount": "New account created.",
	"options.sync.createAccountBtn": "Create Account",
	"options.sync.enterKey": "Enter your Lazarus Sync Key",
	"options.sync.key": "Sync Key",
	"options.sync.now": "Sync Now",
	"options.sync.setup": "Setup Sync",
	"options.sync.setup.btn": "Setup Sync...",
	"options.sync.server": "Sync Server URL",
	"options.sync.account": "Sync Account",
	"options.sync.account.created": "Account created",
	"options.sync.syncing": "Syncing database (this may take some time)...",
	"options.sync.success": "Database synced successfully.",
	"options.sync.loggedIn": "Logged in.",
	"options.sync.loginWarning": 'Sync is disabled, please <a id="sync-login-warning-link">log back in</a>',
	"options.sync.stopSyncing": "Stop syncing this browser",
	"options.sync.instructions": "You'll need an Interclue account before you can setup Lazarus Sync",
	"options.tests": "Tests",
	"options.runUnitTests": "Run Unit Tests",
  
  "error.accountReset": "Your password has been reset, please login using the new password",
  "error.emailRequired": "Email is required",
  "error.passwordRequired": "Password is required",
  "error.passwordsDoNotMatch": "Passwords do not match",
	"error.server": "Error: Sorry, an error occured and the server cannot perform the required function. '{errMsg}'",
	"error.cannot.find.form": "Error: Cannot find form",
  
  "btn.show.menu.tooltip": "Lazarus is saving this form. \nClick to recover previous versions",
  "error.passwords.do.not.match": "Your new passwords do not match",
  "password.set": "New password set",
  "password.removed": "Password removed",
  "error.server.unknown": "Server Error: Something went wrong and we were unable to complete the request, Sorry :(",
  "error.unable.to.load.encryption.key": "Unable to load encryption key",
  "error.wrong.password": "Incorrect password",
  "password.reset": "Password reset",
}


